[package]
name = "your_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.17.0"
clap = { version = "3", features = ["derive"] }

oxhttp = { version = "0.1.7", features = ["server"]}
